// Comprehensive job data for Lesotho companies
// Jobs tailored to each education level: certificate, diploma, degree

let jobs = []

export const addJob = (jobData) => {
    const job = {
        id: Math.random().toString(36).substr(2, 9),
        ...jobData,
        postedDate: new Date().toISOString(),
        status: 'active'
    }
    jobs.push(job)
    return job
}

export const getJobsByCompany = (companyId) => {
    return jobs.filter(job => job.companyId === companyId)
}

export const getAllJobs = () => {
    return jobs
}

export const getJobById = (jobId) => {
    return jobs.find(job => job.id === jobId)
}

export const updateJobStatus = (jobId, status) => {
    const job = jobs.find(job => job.id === jobId)
    if (job) {
        job.status = status
        return job
    }
    return null
}

// Pre-populated jobs for each Lesotho company with jobs for each education level
export const LESOTHO_JOBS = [
    // Lesotho Tech Solutions - Technology Company
    {
        id: "lts-cert-001",
        companyId: "lesotho-tech-solutions",
        companyName: "Lesotho Tech Solutions",
        title: "IT Support Technician",
        description: "Provide technical support for computer systems and networks. Assist users with hardware and software issues.",
        location: "Maseru",
        type: "full-time",
        category: "Technology",
        salary: "M45,000 - M65,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Basic Computer Skills", "Troubleshooting", "Customer Service"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lts-diploma-001",
        companyId: "lesotho-tech-solutions",
        companyName: "Lesotho Tech Solutions",
        title: "Network Administrator",
        description: "Manage and maintain computer networks. Configure network equipment and ensure system security.",
        location: "Maseru",
        type: "full-time",
        category: "Technology",
        salary: "M70,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Network Configuration", "Cisco Systems", "System Security", "Linux"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lts-degree-001",
        companyId: "lesotho-tech-solutions",
        companyName: "Lesotho Tech Solutions",
        title: "Software Developer",
        description: "Design, develop, and maintain software applications using modern programming languages and frameworks.",
        location: "Maseru",
        type: "full-time",
        category: "Technology",
        salary: "M120,000 - M160,000",
        educationRequired: "degree",
        experienceRequired: "3-5 years",
        requiredSkills: ["JavaScript", "React", "Node.js", "Python", "SQL", "Git"],
        status: "active",
        applications: 15,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Maseru Innovations - Innovation Hub
    {
        id: "mi-cert-001",
        companyId: "maseru-innovations",
        companyName: "Maseru Innovations",
        title: "Digital Marketing Assistant",
        description: "Support digital marketing campaigns and social media management for innovative projects.",
        location: "Maseru",
        type: "full-time",
        category: "Marketing",
        salary: "M40,000 - M55,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Social Media", "Content Creation", "Basic Analytics"],
        status: "active",
        applications: 18,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "mi-diploma-001",
        companyId: "maseru-innovations",
        companyName: "Maseru Innovations",
        title: "Innovation Project Coordinator",
        description: "Coordinate innovation projects and manage stakeholder communications.",
        location: "Maseru",
        type: "full-time",
        category: "Business",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-3 years",
        requiredSkills: ["Project Management", "Communication", "Stakeholder Management"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-11T10:00:00Z"
    },
    {
        id: "mi-degree-001",
        companyId: "maseru-innovations",
        companyName: "Maseru Innovations",
        title: "Innovation Manager",
        description: "Lead innovation initiatives and manage startup incubation programs.",
        location: "Maseru",
        type: "full-time",
        category: "Business",
        salary: "M110,000 - M140,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Innovation Management", "Startup Development", "Strategic Planning", "Business Development"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-08T10:00:00Z"
    },

    // Nedbank Lesotho - Banking Institution
    {
        id: "nl-cert-001",
        companyId: "nedbank-lesotho",
        companyName: "Nedbank Lesotho",
        title: "Bank Teller",
        description: "Handle customer transactions and provide excellent service at bank branches.",
        location: "Maseru",
        type: "full-time",
        category: "Finance",
        salary: "M35,000 - M50,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Customer Service", "Cash Handling", "Basic Accounting"],
        status: "active",
        applications: 25,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "nl-diploma-001",
        companyId: "nedbank-lesotho",
        companyName: "Nedbank Lesotho",
        title: "Credit Analyst",
        description: "Analyze credit applications and assess financial risk for loan approvals.",
        location: "Maseru",
        type: "full-time",
        category: "Finance",
        salary: "M75,000 - M100,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Financial Analysis", "Credit Assessment", "Risk Management", "Excel"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "nl-degree-001",
        companyId: "nedbank-lesotho",
        companyName: "Nedbank Lesotho",
        title: "Financial Advisor",
        description: "Provide financial planning and investment advice to high-net-worth clients.",
        location: "Maseru",
        type: "full-time",
        category: "Finance",
        salary: "M150,000 - M200,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Financial Planning", "Investment Analysis", "Client Relationship Management", "CFA Certification"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Vodacom Lesotho - Telecommunications
    {
        id: "vl-cert-001",
        companyId: "vodacom-lesotho",
        companyName: "Vodacom Lesotho",
        title: "Customer Service Representative",
        description: "Handle customer inquiries and provide support for telecommunications services.",
        location: "Maseru",
        type: "full-time",
        category: "Telecommunications",
        salary: "M38,000 - M52,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Customer Service", "Communication", "Problem Solving"],
        status: "active",
        applications: 22,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "vl-diploma-001",
        companyId: "vodacom-lesotho",
        companyName: "Vodacom Lesotho",
        title: "Network Operations Technician",
        description: "Maintain and troubleshoot telecommunications network infrastructure.",
        location: "Maseru",
        type: "full-time",
        category: "Telecommunications",
        salary: "M68,000 - M90,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Network Maintenance", "Troubleshooting", "Technical Support"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "vl-degree-001",
        companyId: "vodacom-lesotho",
        companyName: "Vodacom Lesotho",
        title: "Telecommunications Engineer",
        description: "Design and implement telecommunications systems and network infrastructure.",
        location: "Maseru",
        type: "full-time",
        category: "Engineering",
        salary: "M130,000 - M170,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Telecommunications Engineering", "Network Design", "Project Management", "RF Engineering"],
        status: "active",
        applications: 11,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Times - Media Company
    {
        id: "lt-cert-001",
        companyId: "lesotho-times",
        companyName: "Lesotho Times",
        title: "Content Assistant",
        description: "Assist with content creation and social media management for news publications.",
        location: "Maseru",
        type: "full-time",
        category: "Media",
        salary: "M32,000 - M45,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Content Writing", "Social Media", "Basic Journalism"],
        status: "active",
        applications: 19,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lt-diploma-001",
        companyId: "lesotho-times",
        companyName: "Lesotho Times",
        title: "Journalist",
        description: "Research and write news articles for print and digital publications.",
        location: "Maseru",
        type: "full-time",
        category: "Media",
        salary: "M55,000 - M75,000",
        educationRequired: "diploma",
        experienceRequired: "1-3 years",
        requiredSkills: ["Journalism", "Research", "Writing", "Interviewing"],
        status: "active",
        applications: 13,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lt-degree-001",
        companyId: "lesotho-times",
        companyName: "Lesotho Times",
        title: "Senior Editor",
        description: "Lead editorial team and oversee content strategy for news publications.",
        location: "Maseru",
        type: "full-time",
        category: "Media",
        salary: "M95,000 - M125,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Editorial Leadership", "Content Strategy", "Media Law", "Team Management"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-08T10:00:00Z"
    },

    // Ministry of Health - Government Ministry
    {
        id: "mh-cert-001",
        companyId: "ministry-health",
        companyName: "Ministry of Health",
        title: "Health Records Clerk",
        description: "Maintain patient records and support administrative functions in healthcare facilities.",
        location: "Maseru",
        type: "full-time",
        category: "Healthcare",
        salary: "M30,000 - M42,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Record Keeping", "Data Entry", "Administrative Support"],
        status: "active",
        applications: 28,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "mh-diploma-001",
        companyId: "ministry-health",
        companyName: "Ministry of Health",
        title: "Community Health Worker",
        description: "Provide health education and basic healthcare services in communities.",
        location: "Various Districts",
        type: "full-time",
        category: "Healthcare",
        salary: "M45,000 - M65,000",
        educationRequired: "diploma",
        experienceRequired: "1-3 years",
        requiredSkills: ["Health Education", "Community Outreach", "Basic Healthcare"],
        status: "active",
        applications: 21,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "mh-degree-001",
        companyId: "ministry-health",
        companyName: "Ministry of Health",
        title: "Public Health Specialist",
        description: "Develop and implement public health programs and policies.",
        location: "Maseru",
        type: "full-time",
        category: "Healthcare",
        salary: "M120,000 - M160,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Public Health", "Program Management", "Policy Development", "Epidemiology"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Ministry of Education - Government Ministry
    {
        id: "me-cert-001",
        companyId: "ministry-education",
        companyName: "Ministry of Education",
        title: "Education Support Assistant",
        description: "Provide administrative support for educational programs and initiatives.",
        location: "Maseru",
        type: "full-time",
        category: "Education",
        salary: "M28,000 - M40,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Data Management", "Communication"],
        status: "active",
        applications: 32,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "me-diploma-001",
        companyId: "ministry-education",
        companyName: "Ministry of Education",
        title: "Education Officer",
        description: "Support curriculum development and educational program implementation.",
        location: "Maseru",
        type: "full-time",
        category: "Education",
        salary: "M55,000 - M75,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Curriculum Development", "Program Implementation", "Educational Assessment"],
        status: "active",
        applications: 18,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "me-degree-001",
        companyId: "ministry-education",
        companyName: "Ministry of Education",
        title: "Education Policy Advisor",
        description: "Develop education policies and provide strategic advice on educational reforms.",
        location: "Maseru",
        type: "full-time",
        category: "Education",
        salary: "M110,000 - M145,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Policy Development", "Education Research", "Strategic Planning", "Stakeholder Engagement"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Ministry of Agriculture - Government Ministry
    {
        id: "ma-cert-001",
        companyId: "ministry-agriculture",
        companyName: "Ministry of Agriculture",
        title: "Agricultural Support Assistant",
        description: "Provide support for agricultural extension services and farmer assistance programs.",
        location: "Maseru",
        type: "full-time",
        category: "Agriculture",
        salary: "M32,000 - M45,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Farmer Outreach", "Basic Agriculture"],
        status: "active",
        applications: 24,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "ma-diploma-001",
        companyId: "ministry-agriculture",
        companyName: "Ministry of Agriculture",
        title: "Agricultural Extension Officer",
        description: "Provide technical advice and support to farmers on agricultural practices.",
        location: "Various Districts",
        type: "full-time",
        category: "Agriculture",
        salary: "M60,000 - M80,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Agricultural Extension", "Crop Management", "Livestock Management", "Farmer Training"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "ma-degree-001",
        companyId: "ministry-agriculture",
        companyName: "Ministry of Agriculture",
        title: "Agricultural Economist",
        description: "Conduct economic analysis and develop policies for agricultural development.",
        location: "Maseru",
        type: "full-time",
        category: "Agriculture",
        salary: "M105,000 - M135,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Agricultural Economics", "Policy Analysis", "Economic Modeling", "Research"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Tourism Board - Tourism Organization
    {
        id: "ltb-cert-001",
        companyId: "lesotho-tourism-board",
        companyName: "Lesotho Tourism Board",
        title: "Tourism Information Assistant",
        description: "Provide tourism information and support visitor services at tourism centers.",
        location: "Maseru",
        type: "full-time",
        category: "Tourism",
        salary: "M35,000 - M48,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Customer Service", "Tourism Information", "Communication"],
        status: "active",
        applications: 20,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "ltb-diploma-001",
        companyId: "lesotho-tourism-board",
        companyName: "Lesotho Tourism Board",
        title: "Tourism Marketing Coordinator",
        description: "Coordinate tourism marketing campaigns and promotional activities.",
        location: "Maseru",
        type: "full-time",
        category: "Marketing",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-3 years",
        requiredSkills: ["Marketing", "Campaign Management", "Digital Marketing", "Tourism Knowledge"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "ltb-degree-001",
        companyId: "lesotho-tourism-board",
        companyName: "Lesotho Tourism Board",
        title: "Tourism Development Manager",
        description: "Develop tourism strategies and manage tourism development projects.",
        location: "Maseru",
        type: "full-time",
        category: "Tourism",
        salary: "M115,000 - M150,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Tourism Development", "Strategic Planning", "Project Management", "Stakeholder Management"],
        status: "active",
        applications: 10,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Maseru Sun Hotel - Hotel & Hospitality
    {
        id: "msh-cert-001",
        companyId: "maseru-sun-hotel",
        companyName: "Maseru Sun Hotel",
        title: "Hotel Receptionist",
        description: "Handle guest check-ins, reservations, and provide excellent customer service.",
        location: "Maseru",
        type: "full-time",
        category: "Hospitality",
        salary: "M30,000 - M42,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Customer Service", "Reservation Systems", "Communication"],
        status: "active",
        applications: 26,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "msh-diploma-001",
        companyId: "maseru-sun-hotel",
        companyName: "Maseru Sun Hotel",
        title: "Events Coordinator",
        description: "Plan and coordinate events, conferences, and special functions at the hotel.",
        location: "Maseru",
        type: "full-time",
        category: "Hospitality",
        salary: "M55,000 - M75,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Event Planning", "Customer Service", "Vendor Management", "Budgeting"],
        status: "active",
        applications: 15,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "msh-degree-001",
        companyId: "maseru-sun-hotel",
        companyName: "Maseru Sun Hotel",
        title: "Hotel Operations Manager",
        description: "Oversee hotel operations, manage staff, and ensure excellent guest experiences.",
        location: "Maseru",
        type: "full-time",
        category: "Hospitality",
        salary: "M125,000 - M165,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Hotel Management", "Operations Management", "Team Leadership", "Customer Experience"],
        status: "active",
        applications: 11,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Construction Co. - Construction Company
    {
        id: "lcc-cert-001",
        companyId: "lesotho-construction-co",
        companyName: "Lesotho Construction Co.",
        title: "Construction Site Assistant",
        description: "Provide support on construction sites and assist with basic construction tasks.",
        location: "Maseru",
        type: "full-time",
        category: "Construction",
        salary: "M38,000 - M52,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Basic Construction", "Safety Procedures", "Site Support"],
        status: "active",
        applications: 22,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lcc-diploma-001",
        companyId: "lesotho-construction-co",
        companyName: "Lesotho Construction Co.",
        title: "Quantity Surveyor Assistant",
        description: "Assist with quantity surveying, cost estimation, and project documentation.",
        location: "Maseru",
        type: "full-time",
        category: "Construction",
        salary: "M70,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Quantity Surveying", "Cost Estimation", "Project Documentation", "AutoCAD"],
        status: "active",
        applications: 13,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lcc-degree-001",
        companyId: "lesotho-construction-co",
        companyName: "Lesotho Construction Co.",
        title: "Project Manager",
        description: "Manage construction projects from planning to completion, ensuring quality and budget compliance.",
        location: "Maseru",
        type: "full-time",
        category: "Construction",
        salary: "M140,000 - M180,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Project Management", "Construction Management", "Contract Management", "Risk Management"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-08T10:00:00Z"
    },

    // Lesotho Electricity Company - Utility Company
    {
        id: "lec-cert-001",
        companyId: "lesotho-electricity-company",
        companyName: "Lesotho Electricity Company",
        title: "Customer Service Assistant",
        description: "Handle customer inquiries and billing support for electricity services.",
        location: "Maseru",
        type: "full-time",
        category: "Utilities",
        salary: "M33,000 - M46,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Customer Service", "Billing Support", "Data Entry"],
        status: "active",
        applications: 19,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "lec-diploma-001",
        companyId: "lesotho-electricity-company",
        companyName: "Lesotho Electricity Company",
        title: "Electrical Technician",
        description: "Maintain and repair electrical distribution systems and equipment.",
        location: "Various Locations",
        type: "full-time",
        category: "Engineering",
        salary: "M75,000 - M100,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Electrical Maintenance", "Troubleshooting", "Safety Procedures", "Technical Documentation"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "lec-degree-001",
        companyId: "lesotho-electricity-company",
        companyName: "Lesotho Electricity Company",
        title: "Electrical Engineer",
        description: "Design and oversee electrical systems and infrastructure projects.",
        location: "Maseru",
        type: "full-time",
        category: "Engineering",
        salary: "M135,000 - M175,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Electrical Engineering", "Power Systems", "Project Management", "Regulatory Compliance"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Lesotho Revenue Authority - Government Agency
    {
        id: "lra-cert-001",
        companyId: "lesotho-revenue-authority",
        companyName: "Lesotho Revenue Authority",
        title: "Tax Records Clerk",
        description: "Maintain tax records and provide administrative support for tax services.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M31,000 - M44,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Record Keeping", "Data Entry", "Administrative Support"],
        status: "active",
        applications: 23,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "lra-diploma-001",
        companyId: "lesotho-revenue-authority",
        companyName: "Lesotho Revenue Authority",
        title: "Tax Compliance Officer",
        description: "Assist taxpayers with compliance requirements and process tax returns.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Tax Compliance", "Customer Service", "Documentation", "Basic Accounting"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "lra-degree-001",
        companyId: "lesotho-revenue-authority",
        companyName: "Lesotho Revenue Authority",
        title: "Tax Policy Analyst",
        description: "Analyze tax policies and develop recommendations for tax administration improvements.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M115,000 - M150,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Tax Policy", "Economic Analysis", "Policy Development", "Research"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Pharmaceutical Services - Healthcare Company
    {
        id: "lps-cert-001",
        companyId: "lesotho-pharmaceutical-services",
        companyName: "Lesotho Pharmaceutical Services",
        title: "Pharmacy Assistant",
        description: "Assist pharmacists with dispensing medications and maintaining pharmacy records.",
        location: "Maseru",
        type: "full-time",
        category: "Healthcare",
        salary: "M34,000 - M47,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Pharmacy Support", "Record Keeping", "Customer Service"],
        status: "active",
        applications: 21,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lps-diploma-001",
        companyId: "lesotho-pharmaceutical-services",
        companyName: "Lesotho Pharmaceutical Services",
        title: "Pharmaceutical Technician",
        description: "Prepare and dispense medications under pharmacist supervision.",
        location: "Maseru",
        type: "full-time",
        category: "Healthcare",
        salary: "M55,000 - M75,000",
        educationRequired: "diploma",
        experienceRequired: "1-3 years",
        requiredSkills: ["Medication Preparation", "Pharmacy Operations", "Quality Control", "Inventory Management"],
        status: "active",
        applications: 13,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lps-degree-001",
        companyId: "lesotho-pharmaceutical-services",
        companyName: "Lesotho Pharmaceutical Services",
        title: "Clinical Pharmacist",
        description: "Provide clinical pharmacy services and medication therapy management.",
        location: "Maseru",
        type: "full-time",
        category: "Healthcare",
        salary: "M125,000 - M165,000",
        educationRequired: "degree",
        experienceRequired: "3-5 years",
        requiredSkills: ["Clinical Pharmacy", "Medication Therapy", "Patient Care", "Drug Information"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Chamber of Commerce - Business Association
    {
        id: "lcci-cert-001",
        companyId: "lesotho-chamber-commerce",
        companyName: "Lesotho Chamber of Commerce",
        title: "Administrative Assistant",
        description: "Provide administrative support for chamber operations and member services.",
        location: "Maseru",
        type: "full-time",
        category: "Business",
        salary: "M29,000 - M41,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Communication", "Organization"],
        status: "active",
        applications: 17,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "lcci-diploma-001",
        companyId: "lesotho-chamber-commerce",
        companyName: "Lesotho Chamber of Commerce",
        title: "Business Development Officer",
        description: "Support business development initiatives and member engagement activities.",
        location: "Maseru",
        type: "full-time",
        category: "Business",
        salary: "M60,000 - M80,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Business Development", "Member Relations", "Event Planning", "Marketing"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "lcci-degree-001",
        companyId: "lesotho-chamber-commerce",
        companyName: "Lesotho Chamber of Commerce",
        title: "Policy Advisor",
        description: "Develop business policy recommendations and advocate for business interests.",
        location: "Maseru",
        type: "full-time",
        category: "Business",
        salary: "M110,000 - M145,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Policy Analysis", "Business Advocacy", "Economic Development", "Stakeholder Engagement"],
        status: "active",
        applications: 6,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Statistics Lesotho - Government Agency
    {
        id: "bos-cert-001",
        companyId: "statistics-lesotho",
        companyName: "Statistics Lesotho",
        title: "Data Collection Assistant",
        description: "Assist with data collection activities and survey administration.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M32,000 - M45,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Data Collection", "Survey Administration", "Basic Data Entry"],
        status: "active",
        applications: 18,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "bos-diploma-001",
        companyId: "statistics-lesotho",
        companyName: "Statistics Lesotho",
        title: "Statistical Assistant",
        description: "Assist with statistical analysis and data processing for research projects.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Statistical Analysis", "Data Processing", "SPSS/Stata", "Research Support"],
        status: "active",
        applications: 11,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "bos-degree-001",
        companyId: "statistics-lesotho",
        companyName: "Statistics Lesotho",
        title: "Senior Statistician",
        description: "Lead statistical research projects and provide statistical expertise for policy development.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M120,000 - M160,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Advanced Statistics", "Research Methodology", "Data Analysis", "Policy Support"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Agribusiness - Agribusiness Company
    {
        id: "la-cert-001",
        companyId: "lesotho-agribusiness",
        companyName: "Lesotho Agribusiness",
        title: "Farm Support Assistant",
        description: "Provide support for farming operations and agricultural activities.",
        location: "Leribe",
        type: "full-time",
        category: "Agriculture",
        salary: "M30,000 - M42,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Farm Support", "Basic Agriculture", "Record Keeping"],
        status: "active",
        applications: 20,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "la-diploma-001",
        companyId: "lesotho-agribusiness",
        companyName: "Lesotho Agribusiness",
        title: "Agricultural Production Officer",
        description: "Oversee agricultural production and manage farming operations.",
        location: "Leribe",
        type: "full-time",
        category: "Agriculture",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Agricultural Production", "Farm Management", "Crop Management", "Quality Control"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "la-degree-001",
        companyId: "lesotho-agribusiness",
        companyName: "Lesotho Agribusiness",
        title: "Agribusiness Manager",
        description: "Manage agribusiness operations and develop agricultural business strategies.",
        location: "Leribe",
        type: "full-time",
        category: "Agriculture",
        salary: "M115,000 - M150,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Agribusiness Management", "Strategic Planning", "Supply Chain Management", "Business Development"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Ministry of Development Planning - Government Ministry
    {
        id: "mdp-cert-001",
        companyId: "ministry-development-planning",
        companyName: "Ministry of Development Planning",
        title: "Planning Support Assistant",
        description: "Provide administrative support for development planning activities.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M31,000 - M44,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Data Management", "Planning Support"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "mdp-diploma-001",
        companyId: "ministry-development-planning",
        companyName: "Ministry of Development Planning",
        title: "Development Planning Officer",
        description: "Support development planning initiatives and project coordination.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M70,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Development Planning", "Project Coordination", "Data Analysis", "Report Writing"],
        status: "active",
        applications: 11,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "mdp-degree-001",
        companyId: "ministry-development-planning",
        companyName: "Ministry of Development Planning",
        title: "Senior Development Planner",
        description: "Lead development planning strategies and policy formulation.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M130,000 - M170,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Development Planning", "Policy Formulation", "Strategic Planning", "Economic Analysis"],
        status: "active",
        applications: 6,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Ministry of Public Works - Government Ministry
    {
        id: "mpw-cert-001",
        companyId: "ministry-public-works",
        companyName: "Ministry of Public Works",
        title: "Works Support Assistant",
        description: "Provide administrative support for public works projects and maintenance.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M33,000 - M46,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Project Documentation", "Basic Construction Knowledge"],
        status: "active",
        applications: 19,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "mpw-diploma-001",
        companyId: "ministry-public-works",
        companyName: "Ministry of Public Works",
        title: "Public Works Inspector",
        description: "Inspect public infrastructure projects and ensure compliance with standards.",
        location: "Various Locations",
        type: "full-time",
        category: "Government",
        salary: "M75,000 - M100,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Infrastructure Inspection", "Quality Control", "Technical Documentation", "Safety Compliance"],
        status: "active",
        applications: 13,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "mpw-degree-001",
        companyId: "ministry-public-works",
        companyName: "Ministry of Public Works",
        title: "Infrastructure Development Manager",
        description: "Manage public infrastructure development projects and strategic planning.",
        location: "Maseru",
        type: "full-time",
        category: "Government",
        salary: "M140,000 - M180,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Infrastructure Management", "Project Management", "Strategic Planning", "Contract Management"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Research Institute - Research Institution
    {
        id: "lri-cert-001",
        companyId: "lesotho-research-institute",
        companyName: "Lesotho Research Institute",
        title: "Research Support Assistant",
        description: "Provide administrative and logistical support for research activities.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M32,000 - M45,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Research Support", "Data Management"],
        status: "active",
        applications: 15,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lri-diploma-001",
        companyId: "lesotho-research-institute",
        companyName: "Lesotho Research Institute",
        title: "Research Assistant",
        description: "Assist researchers with data collection, analysis, and fieldwork.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M60,000 - M80,000",
        educationRequired: "diploma",
        experienceRequired: "1-3 years",
        requiredSkills: ["Research Methods", "Data Collection", "Data Analysis", "Fieldwork"],
        status: "active",
        applications: 10,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lri-degree-001",
        companyId: "lesotho-research-institute",
        companyName: "Lesotho Research Institute",
        title: "Senior Research Fellow",
        description: "Lead research projects and contribute to academic publications and policy development.",
        location: "Maseru",
        type: "full-time",
        category: "Research",
        salary: "M125,000 - M165,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Research Methodology", "Academic Writing", "Policy Analysis", "Project Leadership"],
        status: "active",
        applications: 5,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Fashion House - Fashion Company
    {
        id: "lfh-cert-001",
        companyId: "lesotho-fashion-house",
        companyName: "Lesotho Fashion House",
        title: "Fashion Assistant",
        description: "Assist with fashion design and production activities.",
        location: "Maseru",
        type: "full-time",
        category: "Fashion",
        salary: "M35,000 - M48,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Fashion Design", "Sewing", "Creative Skills"],
        status: "active",
        applications: 18,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "lfh-diploma-001",
        companyId: "lesotho-fashion-house",
        companyName: "Lesotho Fashion House",
        title: "Fashion Designer",
        description: "Design clothing and accessories for local and international markets.",
        location: "Maseru",
        type: "full-time",
        category: "Fashion",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-3 years",
        requiredSkills: ["Fashion Design", "Pattern Making", "Fabric Knowledge", "Adobe Creative Suite"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "lfh-degree-001",
        companyId: "lesotho-fashion-house",
        companyName: "Lesotho Fashion House",
        title: "Creative Director",
        description: "Lead fashion design teams and develop brand strategies.",
        location: "Maseru",
        type: "full-time",
        category: "Fashion",
        salary: "M120,000 - M155,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Fashion Design", "Brand Management", "Team Leadership", "Market Analysis"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Lesotho Architectural Design - Architecture Firm
    {
        id: "lad-cert-001",
        companyId: "lesotho-architectural-design",
        companyName: "Lesotho Architectural Design",
        title: "Architectural Assistant",
        description: "Provide support for architectural design and drafting activities.",
        location: "Maseru",
        type: "full-time",
        category: "Architecture",
        salary: "M40,000 - M55,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Drafting", "AutoCAD", "Basic Design"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "lad-diploma-001",
        companyId: "lesotho-architectural-design",
        companyName: "Lesotho Architectural Design",
        title: "Architectural Technician",
        description: "Create technical drawings and assist with building design projects.",
        location: "Maseru",
        type: "full-time",
        category: "Architecture",
        salary: "M75,000 - M100,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["AutoCAD", "Revit", "Technical Drawing", "Building Codes"],
        status: "active",
        applications: 10,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "lad-degree-001",
        companyId: "lesotho-architectural-design",
        companyName: "Lesotho Architectural Design",
        title: "Senior Architect",
        description: "Lead architectural design projects and manage client relationships.",
        location: "Maseru",
        type: "full-time",
        category: "Architecture",
        salary: "M140,000 - M180,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Architectural Design", "Project Management", "Client Relations", "Sustainable Design"],
        status: "active",
        applications: 6,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Manufacturing Co. - Manufacturing Company
    {
        id: "lmco-cert-001",
        companyId: "lesotho-manufacturing-co",
        companyName: "Lesotho Manufacturing Co.",
        title: "Production Assistant",
        description: "Assist with manufacturing operations and quality control.",
        location: "Maseru",
        type: "full-time",
        category: "Manufacturing",
        salary: "M36,000 - M50,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Manufacturing Support", "Quality Control", "Safety Procedures"],
        status: "active",
        applications: 20,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lmco-diploma-001",
        companyId: "lesotho-manufacturing-co",
        companyName: "Lesotho Manufacturing Co.",
        title: "Manufacturing Supervisor",
        description: "Supervise production lines and ensure operational efficiency.",
        location: "Maseru",
        type: "full-time",
        category: "Manufacturing",
        salary: "M70,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Production Management", "Quality Assurance", "Team Supervision", "Lean Manufacturing"],
        status: "active",
        applications: 15,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lmco-degree-001",
        companyId: "lesotho-manufacturing-co",
        companyName: "Lesotho Manufacturing Co.",
        title: "Operations Manager",
        description: "Manage manufacturing operations and implement process improvements.",
        location: "Maseru",
        type: "full-time",
        category: "Manufacturing",
        salary: "M130,000 - M170,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Operations Management", "Process Improvement", "Supply Chain", "Quality Management"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Retail Group - Retail Company
    {
        id: "lrg-cert-001",
        companyId: "lesotho-retail-group",
        companyName: "Lesotho Retail Group",
        title: "Retail Sales Assistant",
        description: "Provide customer service and assist with sales in retail stores.",
        location: "Maseru",
        type: "full-time",
        category: "Retail",
        salary: "M28,000 - M40,000",
        educationRequired: "certificate",
        experienceRequired: "0-1 years",
        requiredSkills: ["Customer Service", "Sales", "Product Knowledge"],
        status: "active",
        applications: 25,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "lrg-diploma-001",
        companyId: "lesotho-retail-group",
        companyName: "Lesotho Retail Group",
        title: "Store Manager",
        description: "Manage retail store operations and staff performance.",
        location: "Maseru",
        type: "full-time",
        category: "Retail",
        salary: "M65,000 - M85,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Retail Management", "Staff Supervision", "Inventory Control", "Customer Relations"],
        status: "active",
        applications: 18,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "lrg-degree-001",
        companyId: "lesotho-retail-group",
        companyName: "Lesotho Retail Group",
        title: "Retail Operations Director",
        description: "Oversee retail operations and develop business strategies.",
        location: "Maseru",
        type: "full-time",
        category: "Retail",
        salary: "M125,000 - M160,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Retail Strategy", "Operations Management", "Business Development", "Financial Analysis"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Lesotho Logistics Services - Logistics Company
    {
        id: "lls-cert-001",
        companyId: "lesotho-logistics-services",
        companyName: "Lesotho Logistics Services",
        title: "Logistics Assistant",
        description: "Assist with warehouse operations and inventory management.",
        location: "Maseru",
        type: "full-time",
        category: "Logistics",
        salary: "M34,000 - M47,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Warehouse Operations", "Inventory Management", "Data Entry"],
        status: "active",
        applications: 22,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "lls-diploma-001",
        companyId: "lesotho-logistics-services",
        companyName: "Lesotho Logistics Services",
        title: "Logistics Coordinator",
        description: "Coordinate transportation and distribution activities.",
        location: "Maseru",
        type: "full-time",
        category: "Logistics",
        salary: "M68,000 - M90,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Supply Chain Coordination", "Transportation Management", "Inventory Control", "Customer Service"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "lls-degree-001",
        companyId: "lesotho-logistics-services",
        companyName: "Lesotho Logistics Services",
        title: "Supply Chain Manager",
        description: "Manage supply chain operations and optimize logistics processes.",
        location: "Maseru",
        type: "full-time",
        category: "Logistics",
        salary: "M135,000 - M175,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Supply Chain Management", "Logistics Optimization", "Vendor Relations", "Process Improvement"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Mining Corporation - Mining Company
    {
        id: "lmc-cert-001",
        companyId: "lesotho-mining-corporation",
        companyName: "Lesotho Mining Corporation",
        title: "Mining Support Assistant",
        description: "Provide administrative support for mining operations.",
        location: "Leribe",
        type: "full-time",
        category: "Mining",
        salary: "M42,000 - M56,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Safety Awareness", "Data Management"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lmc-diploma-001",
        companyId: "lesotho-mining-corporation",
        companyName: "Lesotho Mining Corporation",
        title: "Mining Technician",
        description: "Operate mining equipment and ensure safety compliance.",
        location: "Leribe",
        type: "full-time",
        category: "Mining",
        salary: "M80,000 - M105,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Mining Operations", "Equipment Operation", "Safety Procedures", "Technical Documentation"],
        status: "active",
        applications: 9,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lmc-degree-001",
        companyId: "lesotho-mining-corporation",
        companyName: "Lesotho Mining Corporation",
        title: "Mining Engineer",
        description: "Design mining operations and manage extraction projects.",
        location: "Leribe",
        type: "full-time",
        category: "Mining",
        salary: "M150,000 - M190,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Mining Engineering", "Project Management", "Environmental Compliance", "Resource Planning"],
        status: "active",
        applications: 5,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Environmental Services - Environmental Company
    {
        id: "les-cert-001",
        companyId: "lesotho-environmental-services",
        companyName: "Lesotho Environmental Services",
        title: "Environmental Assistant",
        description: "Assist with environmental monitoring and conservation activities.",
        location: "Maseru",
        type: "full-time",
        category: "Environmental",
        salary: "M33,000 - M46,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Environmental Monitoring", "Data Collection", "Conservation Support"],
        status: "active",
        applications: 17,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "les-diploma-001",
        companyId: "lesotho-environmental-services",
        companyName: "Lesotho Environmental Services",
        title: "Environmental Officer",
        description: "Conduct environmental assessments and implement conservation programs.",
        location: "Various Locations",
        type: "full-time",
        category: "Environmental",
        salary: "M70,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Environmental Assessment", "Conservation Planning", "Data Analysis", "Report Writing"],
        status: "active",
        applications: 13,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "les-degree-001",
        companyId: "lesotho-environmental-services",
        companyName: "Lesotho Environmental Services",
        title: "Environmental Manager",
        description: "Lead environmental programs and ensure regulatory compliance.",
        location: "Maseru",
        type: "full-time",
        category: "Environmental",
        salary: "M130,000 - M170,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Environmental Management", "Regulatory Compliance", "Sustainability Planning", "Stakeholder Engagement"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-10T10:00:00Z"
    },

    // Lesotho Legal Services - Legal Firm
    {
        id: "lls-cert-001",
        companyId: "lesotho-legal-services",
        companyName: "Lesotho Legal Services",
        title: "Legal Assistant",
        description: "Provide administrative support for legal services and case management.",
        location: "Maseru",
        type: "full-time",
        category: "Legal",
        salary: "M37,000 - M50,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Document Management", "Legal Research"],
        status: "active",
        applications: 14,
        postedDate: "2024-03-17T10:00:00Z"
    },
    {
        id: "lls-diploma-001",
        companyId: "lesotho-legal-services",
        companyName: "Lesotho Legal Services",
        title: "Paralegal",
        description: "Assist lawyers with legal research, document preparation, and case management.",
        location: "Maseru",
        type: "full-time",
        category: "Legal",
        salary: "M75,000 - M100,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Legal Research", "Document Preparation", "Case Management", "Client Communication"],
        status: "active",
        applications: 11,
        postedDate: "2024-03-14T10:00:00Z"
    },
    {
        id: "lls-degree-001",
        companyId: "lesotho-legal-services",
        companyName: "Lesotho Legal Services",
        title: "Senior Legal Counsel",
        description: "Provide legal advice and represent clients in legal matters.",
        location: "Maseru",
        type: "full-time",
        category: "Legal",
        salary: "M160,000 - M200,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Legal Practice", "Client Representation", "Contract Law", "Litigation"],
        status: "active",
        applications: 6,
        postedDate: "2024-03-11T10:00:00Z"
    },

    // Lesotho Insurance Group - Insurance Company
    {
        id: "lig-cert-001",
        companyId: "lesotho-insurance-group",
        companyName: "Lesotho Insurance Group",
        title: "Insurance Support Assistant",
        description: "Provide administrative support for insurance services and claims processing.",
        location: "Maseru",
        type: "full-time",
        category: "Insurance",
        salary: "M35,000 - M48,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Customer Service", "Data Entry"],
        status: "active",
        applications: 19,
        postedDate: "2024-03-15T10:00:00Z"
    },
    {
        id: "lig-diploma-001",
        companyId: "lesotho-insurance-group",
        companyName: "Lesotho Insurance Group",
        title: "Claims Officer",
        description: "Process insurance claims and assess risk for policy underwriting.",
        location: "Maseru",
        type: "full-time",
        category: "Insurance",
        salary: "M72,000 - M95,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Claims Processing", "Risk Assessment", "Customer Service", "Insurance Knowledge"],
        status: "active",
        applications: 15,
        postedDate: "2024-03-12T10:00:00Z"
    },
    {
        id: "lig-degree-001",
        companyId: "lesotho-insurance-group",
        companyName: "Lesotho Insurance Group",
        title: "Insurance Manager",
        description: "Manage insurance operations and develop underwriting strategies.",
        location: "Maseru",
        type: "full-time",
        category: "Insurance",
        salary: "M140,000 - M180,000",
        educationRequired: "degree",
        experienceRequired: "4-6 years",
        requiredSkills: ["Insurance Management", "Underwriting", "Risk Management", "Financial Analysis"],
        status: "active",
        applications: 8,
        postedDate: "2024-03-09T10:00:00Z"
    },

    // Lesotho Consulting Firm - Consulting Company
    {
        id: "lcf-cert-001",
        companyId: "lesotho-consulting-firm",
        companyName: "Lesotho Consulting Firm",
        title: "Consulting Assistant",
        description: "Provide administrative support for consulting projects and client management.",
        location: "Maseru",
        type: "full-time",
        category: "Consulting",
        salary: "M38,000 - M52,000",
        educationRequired: "certificate",
        experienceRequired: "0-2 years",
        requiredSkills: ["Administrative Support", "Data Management", "Client Communication"],
        status: "active",
        applications: 16,
        postedDate: "2024-03-16T10:00:00Z"
    },
    {
        id: "lcf-diploma-001",
        companyId: "lesotho-consulting-firm",
        companyName: "Lesotho Consulting Firm",
        title: "Business Analyst",
        description: "Analyze business processes and provide recommendations for improvement.",
        location: "Maseru",
        type: "full-time",
        category: "Consulting",
        salary: "M78,000 - M105,000",
        educationRequired: "diploma",
        experienceRequired: "2-4 years",
        requiredSkills: ["Business Analysis", "Process Improvement", "Data Analysis", "Report Writing"],
        status: "active",
        applications: 12,
        postedDate: "2024-03-13T10:00:00Z"
    },
    {
        id: "lcf-degree-001",
        companyId: "lesotho-consulting-firm",
        companyName: "Lesotho Consulting Firm",
        title: "Senior Consultant",
        description: "Lead consulting projects and provide strategic advice to clients.",
        location: "Maseru",
        type: "full-time",
        category: "Consulting",
        salary: "M155,000 - M195,000",
        educationRequired: "degree",
        experienceRequired: "5+ years",
        requiredSkills: ["Strategic Consulting", "Project Management", "Client Relations", "Industry Expertise"],
        status: "active",
        applications: 7,
        postedDate: "2024-03-10T10:00:00Z"
    }
]

// Initialize jobs array with pre-populated data
jobs = [...LESOTHO_JOBS]
